### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by djooko** [squarechip/timeline#10]
i wanted to make a right to left timeline so i picked your plugin . i tried but i think its not an rtl  friend  yet? thanks bro

**Comment by squarechip** [comment]
Hey. You could just set the startIndex setting to the number of your items in the timeline minus the number of items in the viewport. This will make it start at the end, so right to left.

Or rather than working the number out yourself, you could just add a random high startIndex of say 99 and the plugin will automatically use the highest startIndex possible. This will just leave a warning in the console of the developer tools though (but this warning will tell you the largest number you can use for the startIndex based on your timeline so you can then go back and change it).

Hope that helps.

**Comment by djooko** [comment]
Thank so much for the quick answer bro!
i'll try that :)

**Comment by ismailcseku** [comment]
Hi, 
I also wanted to use this plugin into a RTL website. But failed to figured out how to make it working for RTL mode. I tried your startindex to 99 trick but it didn't work. Can you please create a RTL example so that we can understand it clearly. Also you can use an option like owl carousel (rtl: true) feature.

Thanks
ismail
