### ISSUE TITLE
Timeline items with large content is never shown on smaller screens

### ISSUE THREAD

**Issue by xiegeo** [squarechip/timeline#2]
isElementInViewport is never true if element is bigger than viewport.

This problem is especially acute when viewing a vertical timeline in a mobile device on landscape. You can also reproduce this problem on a desktop browser by lowering the height of the window to less than the height of the item.

I think one way to solve this problem is by having a timeline item show up when the top of the item reaches a certain percentage of the page, as an additional trigger.

**Comment by squarechip** [comment]
Hi. Thanks for letting me know about this issue. 

I have amended the 'isElementInViewport' function to check whether an element is partially visible rather than fully visible. An element will now scroll into view once the top of it is <= 85% from the top of the page.

I will add this figure as a setting in a future release so that you can choose your own trigger distance from the top of the page.

**Comment by xiegeo** [comment]
Thank you, it works great!
