### ISSUE TITLE
Horizontal mode doesn't work with Bootstrap 3 Modals

### ISSUE THREAD

**Issue by Bryuk** [squarechip/timeline#3]
If i place timeline div inside `<div class="modal-body">` of Bootstrap 3 Modal and set mode to horizontal - it's not showing any content. If I leave default options - vertical timeline shows just fine.

Can you please address this issue. I really love this simple timeline plugin and I need to use it in Bootstrap Modals.

**Comment by squarechip** [comment]
Hi,

The issue is that the heights and widths of the horizontal timeline elements are calculated using the height/width of its containing element. In this case, the modal's height and width is zero as it is hidden, so you need to initialize the timeline plugin once the modal is visible, rather than on page load.

You can do this using one of the Bootstrap Modal Events here: https://getbootstrap.com/docs/4.0/components/modal/#events

The code below should work for you. Just change the #yourModalID for the ID of your modal and add in your other configuration options.

```javascript
$(document).ready(function(){
  $('#yourModalID').on('shown.bs.modal', function (e) {
    $('.timeline').timeline({
      mode: 'horizontal'
    });
  });
});
```

I will be pushing an updated version of the plugin soon...maybe over the weekend when I get the time. This will include further config options such as being able to set how many items slide on each click of the horizontal timeline which may be useful to you.

Any issues with the above, let me know.

**Comment by Bryuk** [comment]
Hi,
Thanks. This helped and I was able to show timeline in both horizontal and vertical modes.
But...
I ran into another issue with IE11 and IE10 browsers. There is several errors in JS code. First is that IE doesn't like .remove() functions and throws an error. Second is another error, which I'm not sure where exactly, but it happens when I resize browser. 
I have tested this on few computers in different versions of IE, so you should be able to reproduce it pretty easily. Any chance this can be fixed soon? I feel this is the only reason left that stops me to implement this plugin...

**Comment by squarechip** [comment]
Sorry the native .remove() method is only supported in IE Edge. I'll amend this part to use the Node.removeChild() method instead which is supported by older versions of IE. This will sort the errors you are getting.

I'll push this as part of version 1.1.2 hopefully later today, but if not, over the weekend.
